import this

map0 = [
    "XXXXXXXXXXXXXXXXXXXX",
    "OXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "OXXXXXXXXXXXXXXXXXXX"
]

room0 = [

]
